/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANURUDDHA
 */
public class GRN extends javax.swing.JPanel {

    DecimalFormat df = new DecimalFormat("00.00");

    /**
     * Creates new form Invoice
     */
    public GRN() {
        initComponents();
        batchNo();
        itemCombo();
    }

    void batchNo() {
        try {
            ResultSet rs = JDBC.getdata("select MAX(batch_no) FROM stock");
            while (rs.next()) {
                String batch1 = rs.getString("max(batch_no)");
                int batch2 = Integer.parseInt(batch1.substring(2));
                int batch3 = (batch2 + 1);
                batch_no.setText("KR" + batch3);
            }
        } catch (Exception e) {
            batch_no.setText("KR" + 15000001);
        }
    }

    void itemCombo() {
        try {
            ResultSet rs = JDBC.getdata("SELECT * FROM item WHERE status='Active'");
            Vector v = new Vector();
            while (rs.next()) {
                v.add(rs.getString(5));
            }
            jCGRN_item.setModel(new DefaultComboBoxModel(v));
            //jCItem_item.setModel(new DefaultComboBoxModel(v));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void addTable() {
        String iid = null;
        String iname = null;
        try {
            ResultSet rs = JDBC.getdata("SELECT * FROM item WHERE item_combo='" + jCGRN_item.getSelectedItem().toString() + "'");
            while (rs.next()) {
                iid = rs.getString("item_id");
                iname = rs.getString("item_name");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        DefaultTableModel d = (DefaultTableModel) jTable3.getModel();
        Vector v = new Vector();
        v.add(iid);
        v.add(iname);
        v.add(jTGRN_up.getText());
        v.add(jTGRN_qty.getText());
        v.add(jTGRN_net.getText());
        d.addRow(v);
        jTGRN_qty.setText("");
        jTGRN_up.setText("");
        jTGRN_net.setText("");
    }

    public boolean checkDuplicate(int columnIndex, JTable jt, String iid) {
        DefaultTableModel d = (DefaultTableModel) jTable3.getModel();
        int rowCount = d.getRowCount();
        boolean b = false;
        for (int x = 0; x < rowCount; x++) {
            String tiid = jt.getValueAt(x, columnIndex).toString();
            if (iid.equals(tiid)) {
                b = true;
            }
        }
        return b;
    }

    void GRN_item_count() {
        try {
            DefaultTableModel d = (DefaultTableModel) jTable3.getModel();
            double item_count = 0;
            double gross_amount = 0;
            for (int x = 0; x < d.getRowCount(); x++) {
                item_count = item_count + Double.parseDouble(jTable3.getValueAt(x, 3).toString());
                gross_amount = gross_amount + Double.parseDouble(jTable3.getValueAt(x, 4).toString());
            }
            jTGRN_item_count.setText(df.format(item_count));
            jTGRN_gross_amount.setText(df.format(gross_amount));
            jTGRN_final_net_amount.setText(df.format(gross_amount));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        NewInvoice1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTGRN_qty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jCGRN_item = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jTGRN_up = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTGRN_net = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jPanel30 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jTNew_invoice_invoice_no1 = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jTNew_invoice_invoice_no3 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        batch_no = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jTGRN_cash_settled = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTGRN_final_net_amount = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTGRN_gross_amount = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jTGRN_item_count = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1366, 647));
        setMinimumSize(new java.awt.Dimension(1366, 647));
        setPreferredSize(new java.awt.Dimension(1366, 647));
        setRequestFocusEnabled(false);

        NewInvoice1.setBackground(new java.awt.Color(64, 64, 64));
        NewInvoice1.setMaximumSize(new java.awt.Dimension(1364, 655));
        NewInvoice1.setMinimumSize(new java.awt.Dimension(1364, 655));
        NewInvoice1.setPreferredSize(new java.awt.Dimension(1364, 655));

        jPanel6.setBackground(new java.awt.Color(64, 64, 64));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setMaximumSize(new java.awt.Dimension(1350, 212));
        jPanel6.setMinimumSize(new java.awt.Dimension(1350, 212));
        jPanel6.setOpaque(false);

        jButton17.setText("DELETE");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No", "Name", "Unit Price", "Qty", "Net Amount(Rs)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);
        jTable3.getColumnModel().getColumn(3).setResizable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton17)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(64, 64, 64));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(1350, 48));
        jPanel2.setMinimumSize(new java.awt.Dimension(1350, 48));
        jPanel2.setOpaque(false);

        jTGRN_qty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTGRN_qty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTGRN_qtyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTGRN_qtyFocusLost(evt);
            }
        });
        jTGRN_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTGRN_qtyKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Qty :");

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("ADD");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Item  :");

        jCGRN_item.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCGRN_item.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCGRN_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCGRN_itemActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Unit Price(Rs) :");

        jTGRN_up.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTGRN_up.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTGRN_upFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTGRN_upFocusLost(evt);
            }
        });
        jTGRN_up.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTGRN_upKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTGRN_upKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Net Amount (Rs) :");

        jTGRN_net.setEditable(false);
        jTGRN_net.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTGRN_net.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTGRN_netFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(45, 45, 45)
                .addComponent(jCGRN_item, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTGRN_up, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTGRN_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTGRN_net, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTGRN_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTGRN_net, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCGRN_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTGRN_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(64, 64, 64));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setOpaque(false);

        jButton22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton22.setText("SAVE");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButton22)
                .addGap(5, 5, 5))
        );

        jPanel30.setBackground(new java.awt.Color(64, 64, 64));
        jPanel30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel30.setMaximumSize(new java.awt.Dimension(280, 129));
        jPanel30.setMinimumSize(new java.awt.Dimension(280, 129));
        jPanel30.setName(""); // NOI18N
        jPanel30.setOpaque(false);

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Invoice No : ");

        jTNew_invoice_invoice_no1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Supplier : ");

        jTNew_invoice_invoice_no3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Batch No : ");

        batch_no.setEditable(false);
        batch_no.setBackground(new java.awt.Color(0, 0, 0));
        batch_no.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        batch_no.setForeground(new java.awt.Color(255, 255, 255));
        batch_no.setText("KRI20150001");

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel67)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNew_invoice_invoice_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel69)
                .addGap(40, 40, 40)
                .addComponent(jTNew_invoice_invoice_no3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(batch_no, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel70)
                        .addComponent(batch_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel69)
                        .addComponent(jTNew_invoice_invoice_no3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel67)
                        .addComponent(jTNew_invoice_invoice_no1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(64, 64, 64));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.setOpaque(false);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Cash Settled(Rs):");

        jTGRN_cash_settled.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTGRN_cash_settled.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTGRN_cash_settled.setText("00.00");
        jTGRN_cash_settled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTGRN_cash_settledActionPerformed(evt);
            }
        });
        jTGRN_cash_settled.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTGRN_cash_settledFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTGRN_cash_settledFocusLost(evt);
            }
        });
        jTGRN_cash_settled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTGRN_cash_settledKeyTyped(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Net Amount(Rs):");

        jTGRN_final_net_amount.setEditable(false);
        jTGRN_final_net_amount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTGRN_final_net_amount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTGRN_final_net_amount.setText("00.00");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Gross Amount(Rs):");

        jTGRN_gross_amount.setEditable(false);
        jTGRN_gross_amount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTGRN_gross_amount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTGRN_gross_amount.setText("00.00");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addGap(18, 18, 18)
                .addComponent(jTGRN_gross_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addComponent(jTGRN_cash_settled, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel41)
                .addGap(18, 18, 18)
                .addComponent(jTGRN_final_net_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel41)
                        .addComponent(jTGRN_final_net_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel40)
                        .addComponent(jTGRN_cash_settled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel42)
                        .addComponent(jTGRN_gross_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(64, 64, 64));
        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel19.setOpaque(false);

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Item Count:");

        jTGRN_item_count.setEditable(false);
        jTGRN_item_count.setBackground(new java.awt.Color(0, 0, 0));
        jTGRN_item_count.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTGRN_item_count.setForeground(new java.awt.Color(255, 255, 255));
        jTGRN_item_count.setText("0");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTGRN_item_count, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTGRN_item_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout NewInvoice1Layout = new javax.swing.GroupLayout(NewInvoice1);
        NewInvoice1.setLayout(NewInvoice1Layout);
        NewInvoice1Layout.setHorizontalGroup(
            NewInvoice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewInvoice1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewInvoice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1341, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1341, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(NewInvoice1Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(13, 13, 13))
        );
        NewInvoice1Layout.setVerticalGroup(
            NewInvoice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewInvoice1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NewInvoice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NewInvoice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NewInvoice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTGRN_qtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTGRN_qtyFocusLost
        try {
            double up = Double.parseDouble(jTGRN_up.getText());
            double qty = Double.parseDouble(jTGRN_qty.getText());
            jTGRN_net.setText(df.format(up * qty));
        } catch (Exception e) {
//            e.printStackTrace();
        }
    }//GEN-LAST:event_jTGRN_qtyFocusLost

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            if (jTGRN_up.getText().isEmpty() || jTGRN_qty.getText().isEmpty() || jTGRN_net.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Some fields are empty", "Input error", JOptionPane.ERROR_MESSAGE);
            } else {
                ResultSet rs = JDBC.getdata("SELECT * FROM item WHERE item_combo='" + jCGRN_item.getSelectedItem().toString() + "'");
                String iid = "";
                while (rs.next()) {
                    iid = rs.getString("item_id");
                }
                if (checkDuplicate(0, jTable3, iid)) {
                    JOptionPane.showMessageDialog(null, "This item is already entered", "Input error", JOptionPane.ERROR_MESSAGE);
                } else {
                    addTable();
                    GRN_item_count();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jCGRN_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCGRN_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCGRN_itemActionPerformed

    private void jTGRN_upFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTGRN_upFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTGRN_upFocusLost

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        try {
            DefaultTableModel d = (DefaultTableModel) jTable3.getModel();
            if (d.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No items added to save", "Input error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (jTNew_invoice_invoice_no1.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please enter invoice number", "Input error", JOptionPane.ERROR_MESSAGE);
                } else if (jTNew_invoice_invoice_no3.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please enter supplier name", "Input error", JOptionPane.ERROR_MESSAGE);
                } else {
                    int i = JOptionPane.showConfirmDialog(null, "Are you sure you want to save?", "", JOptionPane.YES_NO_OPTION);
                    if (i == 0) {
                        for (int x = 0; x < d.getRowCount(); x++) {
                            JDBC.putdata("INSERT INTO stock VALUES("
                                    + "0,"
                                    + "'" + batch_no.getText() + "',"
                                    + "'" + jTable3.getValueAt(x, 0) + "',"
                                    + "'" + jTable3.getValueAt(x, 1) + "',"
                                    + "'" + jTable3.getValueAt(x, 2) + "',"
                                    + "'" + jTable3.getValueAt(x, 3) + "',"
                                    + "'" + jTable3.getValueAt(x, 0) + "-" + jTable3.getValueAt(x, 1) + "')");
                        }

                        JDBC.putdata("INSERT INTO grn_info VALUES("
                                + "0,"
                                + "'" + jTNew_invoice_invoice_no1.getText() + "',"
                                + "'" + QuickDateTime.date() + "',"
                                + "'" + jTGRN_item_count.getText() + "',"
                                + "'" + jTGRN_final_net_amount.getText() + "',"
                                + "'" + jTNew_invoice_invoice_no3.getText() + "')");

                        JDBC.putdata("INSERT INTO account VALUES("
                                + "0,"
                                + "'" + QuickDateTime.date() + "',"
                                + "'Item purchase',"
                                + "'" + jTGRN_final_net_amount.getText() + "',"
                                + "'Expense')");

                        batchNo();
                        d.setRowCount(0);
                        jTGRN_item_count.setText("0");
                        jTGRN_gross_amount.setText("00.00");
                        jTGRN_final_net_amount.setText("00.00");
                        jTNew_invoice_invoice_no1.setText("");
                        jTNew_invoice_invoice_no3.setText("");
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jTGRN_netFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTGRN_netFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTGRN_netFocusLost

    private void jTGRN_cash_settledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTGRN_cash_settledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTGRN_cash_settledActionPerformed

    private void jTGRN_cash_settledFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTGRN_cash_settledFocusGained
        try {
            jTGRN_cash_settled.setText("");
            jTGRN_final_net_amount.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTGRN_cash_settledFocusGained

    private void jTGRN_cash_settledFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTGRN_cash_settledFocusLost
        try {
            if (jTGRN_cash_settled.getText().equals("")) {
                jTGRN_cash_settled.setText("00.00");
                jTGRN_final_net_amount.setText(jTGRN_gross_amount.getText());
            } else {
                double ga = Double.parseDouble(jTGRN_gross_amount.getText());
                double cs = Double.parseDouble(jTGRN_cash_settled.getText());
                jTGRN_final_net_amount.setText(df.format((ga) + (cs)));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTGRN_cash_settledFocusLost

    private void jTGRN_qtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTGRN_qtyFocusGained
        try {
            jTGRN_net.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTGRN_qtyFocusGained

    private void jTGRN_upFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTGRN_upFocusGained
        try {
            jTGRN_net.setText("");
            jTGRN_qty.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTGRN_upFocusGained

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        try {
            int ii = Integer.parseInt(jTable3.getValueAt(jTable3.getSelectedRow(), 4).toString().trim());
            DefaultTableModel d = (DefaultTableModel) jTable3.getModel();
            if (d.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No data entered", "Input error", JOptionPane.ERROR_MESSAGE);
            } else {
                int i = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected item?", "", JOptionPane.YES_NO_OPTION);
                if (i == 0) {
                    d.removeRow(jTable3.getSelectedRow());
                    GRN_item_count();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No item selected", "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jTGRN_upKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTGRN_upKeyReleased
        //
    }//GEN-LAST:event_jTGRN_upKeyReleased

    private void jTGRN_upKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTGRN_upKeyTyped
        char c = evt.getKeyChar();
        if ((Character.isDigit(c)) || (c == '.')) {
        } else {
            evt.consume();
        }
        String s = jTGRN_up.getText();
        if (s.length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTGRN_upKeyTyped

    private void jTGRN_qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTGRN_qtyKeyTyped
        char c = evt.getKeyChar();
        if ((Character.isDigit(c)) || (c == '.')) {
        } else {
            evt.consume();
        }
        String s = jTGRN_qty.getText();
        if (s.length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTGRN_qtyKeyTyped

    private void jTGRN_cash_settledKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTGRN_cash_settledKeyTyped
        try {
            char c = evt.getKeyChar();
            if ((Character.isDigit(c)) || (c == '.') || (c == '-') || (c == '+')) {
            } else {
                evt.consume();
            }
            String s = jTGRN_cash_settled.getText();
            if (s.length() >= 10) {
                evt.consume();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTGRN_cash_settledKeyTyped
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NewInvoice1;
    private javax.swing.JTextField batch_no;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jCGRN_item;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTGRN_cash_settled;
    private javax.swing.JTextField jTGRN_final_net_amount;
    private javax.swing.JTextField jTGRN_gross_amount;
    private javax.swing.JTextField jTGRN_item_count;
    private javax.swing.JTextField jTGRN_net;
    private javax.swing.JTextField jTGRN_qty;
    private javax.swing.JTextField jTGRN_up;
    private javax.swing.JTextField jTNew_invoice_invoice_no1;
    private javax.swing.JTextField jTNew_invoice_invoice_no3;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
