/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import static interfaces.MainFrame.jDesktopPane1;

/**
 *
 * @author ANURUDDHA
 */
public class Home extends javax.swing.JPanel {
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        picMove();
    }

    void picMove(){
        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    while (true) {
                        for (int i = 1; i < 6; i++) {
                            try {
                                Thread.sleep(5000);
                                hi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hi" + i + ".png")));
                            } catch (Exception e) {
                            }
                        }
                    }
                } catch (Exception e) {
                }
            }
        }).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kr = new javax.swing.JLabel();
        hi = new javax.swing.JLabel();
        invoice = new javax.swing.JButton();
        stock = new javax.swing.JButton();
        expenses = new javax.swing.JButton();
        accounts = new javax.swing.JButton();
        option = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1366, 726));
        setMinimumSize(new java.awt.Dimension(1366, 726));
        setPreferredSize(new java.awt.Dimension(1366, 726));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        kr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kr.png"))); // NOI18N
        jPanel1.add(kr);
        kr.setBounds(750, 270, 320, 320);

        hi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hi1.png"))); // NOI18N
        jPanel1.add(hi);
        hi.setBounds(0, 0, 920, 700);

        invoice.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        invoice.setForeground(new java.awt.Color(64, 64, 64));
        invoice.setText("invoice");
        invoice.setBorderPainted(false);
        invoice.setContentAreaFilled(false);
        invoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        invoice.setFocusPainted(false);
        invoice.setFocusable(false);
        invoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                invoiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                invoiceMouseExited(evt);
            }
        });
        invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceActionPerformed(evt);
            }
        });
        jPanel1.add(invoice);
        invoice.setBounds(1060, 330, 300, 41);

        stock.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        stock.setForeground(new java.awt.Color(64, 64, 64));
        stock.setText("stock");
        stock.setBorderPainted(false);
        stock.setContentAreaFilled(false);
        stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stock.setFocusPainted(false);
        stock.setFocusable(false);
        stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stockMouseExited(evt);
            }
        });
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        jPanel1.add(stock);
        stock.setBounds(1060, 370, 300, 41);

        expenses.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        expenses.setForeground(new java.awt.Color(64, 64, 64));
        expenses.setText("income / expenses");
        expenses.setBorderPainted(false);
        expenses.setContentAreaFilled(false);
        expenses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        expenses.setFocusPainted(false);
        expenses.setFocusable(false);
        expenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                expensesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                expensesMouseExited(evt);
            }
        });
        expenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expensesActionPerformed(evt);
            }
        });
        jPanel1.add(expenses);
        expenses.setBounds(1060, 410, 300, 41);

        accounts.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        accounts.setForeground(new java.awt.Color(64, 64, 64));
        accounts.setText("accounts");
        accounts.setBorderPainted(false);
        accounts.setContentAreaFilled(false);
        accounts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accounts.setFocusPainted(false);
        accounts.setFocusable(false);
        accounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountsMouseExited(evt);
            }
        });
        accounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsActionPerformed(evt);
            }
        });
        jPanel1.add(accounts);
        accounts.setBounds(1060, 450, 300, 41);

        option.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        option.setForeground(new java.awt.Color(64, 64, 64));
        option.setText("option");
        option.setBorderPainted(false);
        option.setContentAreaFilled(false);
        option.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        option.setFocusPainted(false);
        option.setFocusable(false);
        option.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optionMouseExited(evt);
            }
        });
        option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionActionPerformed(evt);
            }
        });
        jPanel1.add(option);
        option.setBounds(1060, 490, 300, 41);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText(". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1050, 520, 300, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 64, 64));
        jLabel2.setText(". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1050, 320, 300, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText(". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1050, 360, 300, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText(". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1050, 400, 300, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText(". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1050, 440, 300, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText(". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(1050, 480, 300, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/h8e.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void invoiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceMouseEntered
        invoice.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_invoiceMouseEntered

    private void invoiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceMouseExited
        invoice.setForeground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_invoiceMouseExited

    private void stockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockMouseEntered
        stock.setForeground(new java.awt.Color(153,153,153));//[153,153,153]
    }//GEN-LAST:event_stockMouseEntered

    private void stockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockMouseExited
        stock.setForeground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_stockMouseExited

    private void expensesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expensesMouseEntered
        expenses.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_expensesMouseEntered

    private void expensesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expensesMouseExited
        expenses.setForeground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_expensesMouseExited

    private void accountsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsMouseEntered
        accounts.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_accountsMouseEntered

    private void accountsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsMouseExited
        accounts.setForeground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_accountsMouseExited

    private void optionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionMouseEntered
        option.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_optionMouseEntered

    private void optionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionMouseExited
        option.setForeground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_optionMouseExited

    private void invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceActionPerformed
        InvoiceMain i=new InvoiceMain();
        jDesktopPane1.removeAll();
        i.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        jDesktopPane1.add(i).setVisible(true);
        
        InvoiceMain.jDPinvoice.removeAll();
        Invoice i2=new Invoice();
        i2.setSize(InvoiceMain.jDPinvoice.getWidth(), InvoiceMain.jDPinvoice.getHeight());
        InvoiceMain.jDPinvoice.add(i2).setVisible(true);
        invoice.setForeground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_invoiceActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        StockMain sm=new StockMain();
        jDesktopPane1.removeAll();
        sm.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        jDesktopPane1.add(sm).setVisible(true);
        
        StockMain.jDPstock.removeAll();
        GRN g=new GRN();
        g.setSize(StockMain.jDPstock.getWidth(), StockMain.jDPstock.getHeight());
        StockMain.jDPstock.add(g).setVisible(true);
        stock.setForeground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_stockActionPerformed

    private void accountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsActionPerformed
        AccountMain am=new AccountMain();
        jDesktopPane1.removeAll();
        am.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        jDesktopPane1.add(am).setVisible(true);
        
        AccountMain.jDPaccounts.removeAll();
        ViewAccounts ae=new ViewAccounts();
        ae.setSize(AccountMain.jDPaccounts.getWidth(), AccountMain.jDPaccounts.getHeight());
        AccountMain.jDPaccounts.add(ae).setVisible(true);
        accounts.setForeground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_accountsActionPerformed

    private void expensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expensesActionPerformed
        ExpensesMain am=new ExpensesMain();
        jDesktopPane1.removeAll();
        am.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        jDesktopPane1.add(am).setVisible(true);
        
        ExpensesMain.jDPexpenses.removeAll();
        AddExpenses ae=new AddExpenses();
        ae.setSize(ExpensesMain.jDPexpenses.getWidth(), ExpensesMain.jDPexpenses.getHeight());
        ExpensesMain.jDPexpenses.add(ae).setVisible(true);
        expenses.setForeground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_expensesActionPerformed

    private void optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionActionPerformed
        jDesktopPane1.removeAll();
        OptionMain i=new OptionMain();
        i.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        jDesktopPane1.add(i).setVisible(true);
        
        OptionMain.jDPoption.removeAll();
        EmployeeRegistration er=new EmployeeRegistration();
        er.setSize(OptionMain.jDPoption.getWidth(), OptionMain.jDPoption.getHeight());
        OptionMain.jDPoption.add(er).setVisible(true);
        option.setForeground(new java.awt.Color(64,64,64));
    }//GEN-LAST:event_optionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton accounts;
    public static javax.swing.JButton expenses;
    private javax.swing.JLabel hi;
    public static javax.swing.JButton invoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kr;
    public static javax.swing.JButton option;
    public static javax.swing.JButton stock;
    // End of variables declaration//GEN-END:variables
}
